version: "3.9"
services:
    elasticsearch:
        image: "elasticsearch:7.14.2"
        ports:
            - "9200:9200"
        environment:
            discovery.type: single-node
            ES_JAVA_OPTS: -Xms128m -Xmx512m
    logstash:
        build: ./logstash
        ports:
            - "5000:5000"
        volumes:
            - ./logstash/pipelines:/usr/share/logstash/pipeline
        environment:
          JDBC_CONNECTION: ${JDBC_CONNECTION}
    kibana:
        image: "kibana:7.14.2"
        ports:
            - "5601:5601"
        environment:
            ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    sqlserver:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        user: root
        ports:
            - "9999:1433"
        environment:
            MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
            ACCEPT_EULA: Y
        volumes:
            - ./sqlserver/data:/var/opt/mssql/data
